CREATE FUNCTION dbo.fnGetDateFromParts
(
	@Year INT,
	@Month INT,
	@Day INT,
	@Time VARCHAR(12)
)
RETURNS SMALLDATETIME
WITH SCHEMABINDING
AS
BEGIN
	DECLARE @ReturnDate SMALLDATETIME;
	IF @Time IS NULL
	BEGIN
		SET @ReturnDate = CONVERT(DATETIME, CONVERT(VARCHAR(10), @Month) + '/' + CONVERT(VARCHAR(10), @Day) + '/' + CONVERT(VARCHAR(10), @Year), 101);
	END
	ELSE
	BEGIN
		SET @ReturnDate = CONVERT(DATETIME, CONVERT(VARCHAR(23), @Year) + '-' + CONVERT(VARCHAR(23), @Month) + '-' + CONVERT(VARCHAR(23), @Day) + ' ' + CONVERT(VARCHAR(23), @Time), 121);
	END
	
	RETURN @ReturnDate;
END;

GO