//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.ObjectModel.Factories.PreflightLinkWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDealJobCycle", Namespace="http://schemas.datacontract.org/2004/07/PreflightLinkWCF")]
    [System.SerializableAttribute()]
    public partial class CustomerDealJobCycle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CycleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DealNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> JobNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerShortName {
            get {
                return this.CustomerShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerShortNameField, value) != true)) {
                    this.CustomerShortNameField = value;
                    this.RaisePropertyChanged("CustomerShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CycleNumber {
            get {
                return this.CycleNumberField;
            }
            set {
                if ((this.CycleNumberField.Equals(value) != true)) {
                    this.CycleNumberField = value;
                    this.RaisePropertyChanged("CycleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DealNumber {
            get {
                return this.DealNumberField;
            }
            set {
                if ((this.DealNumberField.Equals(value) != true)) {
                    this.DealNumberField = value;
                    this.RaisePropertyChanged("DealNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((this.JobNumberField.Equals(value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreflightLinkWCF.IPreflightLinkWCF")]
    public interface IPreflightLinkWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreflightLinkWCF/GetCustomerDealJobCycle", ReplyAction="http://tempuri.org/IPreflightLinkWCF/GetCustomerDealJobCycleResponse")]
        BCS.ObjectModel.Factories.PreflightLinkWCF.CustomerDealJobCycle[] GetCustomerDealJobCycle(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreflightLinkWCF/PostBillableActivity", ReplyAction="http://tempuri.org/IPreflightLinkWCF/PostBillableActivityResponse")]
        void PostBillableActivity(string clientId, string dealNum, string jobNum, string cycleNum, string fileCnt, string pageCnt, string recordedDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreflightLinkWCFChannel : BCS.ObjectModel.Factories.PreflightLinkWCF.IPreflightLinkWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreflightLinkWCFClient : System.ServiceModel.ClientBase<BCS.ObjectModel.Factories.PreflightLinkWCF.IPreflightLinkWCF>, BCS.ObjectModel.Factories.PreflightLinkWCF.IPreflightLinkWCF {
        
        public PreflightLinkWCFClient() {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreflightLinkWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BCS.ObjectModel.Factories.PreflightLinkWCF.CustomerDealJobCycle[] GetCustomerDealJobCycle(string clientId) {
            return base.Channel.GetCustomerDealJobCycle(clientId);
        }
        
        public void PostBillableActivity(string clientId, string dealNum, string jobNum, string cycleNum, string fileCnt, string pageCnt, string recordedDate) {
            base.Channel.PostBillableActivity(clientId, dealNum, jobNum, cycleNum, fileCnt, pageCnt, recordedDate);
        }
    }
}
