//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCSInitialLoadBatch.Preflight {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Preflight.IPreflightLinkWCF")]
    public interface IPreflightLinkWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreflightLinkWCF/GetCustomerDealJobCycle", ReplyAction="http://tempuri.org/IPreflightLinkWCF/GetCustomerDealJobCycleResponse")]
        BCS.ObjectModel.Factories.PreflightLinkWCF.CustomerDealJobCycle[] GetCustomerDealJobCycle(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreflightLinkWCF/PostBillableActivity", ReplyAction="http://tempuri.org/IPreflightLinkWCF/PostBillableActivityResponse")]
        void PostBillableActivity(string clientId, string dealNum, string jobNum, string cycleNum, string fileCnt, string pageCnt, string recordedDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreflightLinkWCFChannel : BCSInitialLoadBatch.Preflight.IPreflightLinkWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreflightLinkWCFClient : System.ServiceModel.ClientBase<BCSInitialLoadBatch.Preflight.IPreflightLinkWCF>, BCSInitialLoadBatch.Preflight.IPreflightLinkWCF {
        
        public PreflightLinkWCFClient() {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreflightLinkWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreflightLinkWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BCS.ObjectModel.Factories.PreflightLinkWCF.CustomerDealJobCycle[] GetCustomerDealJobCycle(string clientId) {
            return base.Channel.GetCustomerDealJobCycle(clientId);
        }
        
        public void PostBillableActivity(string clientId, string dealNum, string jobNum, string cycleNum, string fileCnt, string pageCnt, string recordedDate) {
            base.Channel.PostBillableActivity(clientId, dealNum, jobNum, cycleNum, fileCnt, pageCnt, recordedDate);
        }
    }
}
