CREATE TABLE [dbo].[FrequencyType](
	[EnumKey] [int] NOT NULL,
	[EnumText] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_FrequencyType] PRIMARY KEY CLUSTERED 
(
	[EnumKey] ASC,
	[EnumText] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO