Drop Procedure BCS_UpdateTRPFLTTable
go
Create Procedure BCS_UpdateTRPFLTTable
@BCSFLTTableDetails [BCSFLTTableType] READONLY
as
Begin

Declare @currentdate datetime
set @currentdate = GETDATE()

Declare @FLTUpdateTable Table
(
    ID int identity(1,1),
	[FUNDCODE] [nvarchar](7) NULL,
	[FUNDNAME] [nvarchar](40) NULL,
	[FUNDTYPE] [nvarchar](7) NULL,
	[FUNDTELEACCESSCODE] [nvarchar](3) NULL,
	[FUNDCUSIPNUMBER] [nvarchar](8) NULL,
	[FUNDCHKHEADINGCODE] [nvarchar](2) NULL,
	[FUNDGROUPNUMBER] [nvarchar](11) NULL,
	[FUNDPROSPECTUSINSERT] [nvarchar](1) NULL,
	[FUNDPROSPECTUSINSERT2] [nvarchar](1) NULL,
	[FUNDTICKERSYMBOL] [nvarchar](5) NULL,
	[FUNDDocName] [nvarchar](5) NULL
)

INSERT INTO @FLTUpdateTable([FUNDCODE]
      ,[FUNDNAME]
      ,[FUNDTYPE]
      ,[FUNDTELEACCESSCODE]
      ,[FUNDCUSIPNUMBER]
      ,[FUNDCHKHEADINGCODE]
      ,[FUNDGROUPNUMBER]
      ,[FUNDPROSPECTUSINSERT]
      ,[FUNDPROSPECTUSINSERT2]
      ,[FUNDTICKERSYMBOL]
      ,[FUNDDocName])
 SELECT BCSFLTTableDetails.[FUNDCODE]
      ,BCSFLTTableDetails.[FUNDNAME]
      ,BCSFLTTableDetails.[FUNDTYPE]
      ,BCSFLTTableDetails.[FUNDTELEACCESSCODE]
      ,BCSFLTTableDetails.[FUNDCUSIPNUMBER]
      ,BCSFLTTableDetails.[FUNDCHKHEADINGCODE]
      ,BCSFLTTableDetails.[FUNDGROUPNUMBER]
      ,BCSFLTTableDetails.[FUNDPROSPECTUSINSERT]
      ,BCSFLTTableDetails.[FUNDPROSPECTUSINSERT2]
      ,BCSFLTTableDetails.[FUNDTICKERSYMBOL]
      ,BCSFLTTableDetails.[FUNDDocName]
  FROM @BCSFLTTableDetails BCSFLTTableDetails
  INNER JOIN BCSTRPFLT on  BCSFLTTableDetails.FUNDCUSIPNUMBER = BCSTRPFLT.FUNDCUSIPNUMBER
  EXCEPT 
  SELECT [FUNDCODE]
      ,[FUNDNAME]
      ,[FUNDTYPE]
      ,[FUNDTELEACCESSCODE]
      ,[FUNDCUSIPNUMBER]
      ,[FUNDCHKHEADINGCODE]
      ,[FUNDGROUPNUMBER]
      ,[FUNDPROSPECTUSINSERT]
      ,[FUNDPROSPECTUSINSERT2]
      ,[FUNDTICKERSYMBOL]
      ,[FUNDDocName]
   FROM BCSTRPFLT
   

     UPDATE BCSTRPFLT -- Update the records that have changed but DocName has not changed
		SET    BCSTRPFLT.[FUNDCODE]  = [@FLTUpdateTable].FUNDCODE
			  ,BCSTRPFLT.[FUNDNAME] = [@FLTUpdateTable].[FUNDNAME]
			  ,BCSTRPFLT.[FUNDTYPE] = [@FLTUpdateTable].[FUNDTYPE]
			  ,BCSTRPFLT.[FUNDTELEACCESSCODE] = [@FLTUpdateTable].[FUNDTELEACCESSCODE]
			  ,BCSTRPFLT.[FUNDCUSIPNUMBER] = [@FLTUpdateTable].[FUNDCUSIPNUMBER]
			  ,BCSTRPFLT.[FUNDCHKHEADINGCODE] = [@FLTUpdateTable].[FUNDCHKHEADINGCODE]
			  ,BCSTRPFLT.[FUNDGROUPNUMBER] = [@FLTUpdateTable].[FUNDGROUPNUMBER]
			  ,BCSTRPFLT.[FUNDPROSPECTUSINSERT] = [@FLTUpdateTable].[FUNDPROSPECTUSINSERT]
			  ,BCSTRPFLT.[FUNDPROSPECTUSINSERT2] = [@FLTUpdateTable].[FUNDPROSPECTUSINSERT2]
			  ,BCSTRPFLT.[FUNDTICKERSYMBOL] = [@FLTUpdateTable].[FUNDTICKERSYMBOL]			 
			  ,BCSTRPFLT.[DateFLTRecordHasChanged] = @currentdate
		FROM   BCSTRPFLT
		INNER JOIN @FLTUpdateTable 
			 ON BCSTRPFLT.FUNDCUSIPNUMBER = [@FLTUpdateTable].FUNDCUSIPNUMBER    
				AND BCSTRPFLT.FUNDDocName = [@FLTUpdateTable].FUNDDocName
				
     UPDATE BCSTRPFLT -- Update the records that have changed and DocName has also changed
		SET    BCSTRPFLT.[FUNDCODE]  = [@FLTUpdateTable].FUNDCODE
			  ,BCSTRPFLT.[FUNDNAME] = [@FLTUpdateTable].[FUNDNAME]
			  ,BCSTRPFLT.[FUNDTYPE] = [@FLTUpdateTable].[FUNDTYPE]
			  ,BCSTRPFLT.[FUNDTELEACCESSCODE] = [@FLTUpdateTable].[FUNDTELEACCESSCODE]
			  ,BCSTRPFLT.[FUNDCUSIPNUMBER] = [@FLTUpdateTable].[FUNDCUSIPNUMBER]
			  ,BCSTRPFLT.[FUNDCHKHEADINGCODE] = [@FLTUpdateTable].[FUNDCHKHEADINGCODE]
			  ,BCSTRPFLT.[FUNDGROUPNUMBER] = [@FLTUpdateTable].[FUNDGROUPNUMBER]
			  ,BCSTRPFLT.[FUNDPROSPECTUSINSERT] = [@FLTUpdateTable].[FUNDPROSPECTUSINSERT]
			  ,BCSTRPFLT.[FUNDPROSPECTUSINSERT2] = [@FLTUpdateTable].[FUNDPROSPECTUSINSERT2]
			  ,BCSTRPFLT.[FUNDTICKERSYMBOL] = [@FLTUpdateTable].[FUNDTICKERSYMBOL]
			  ,BCSTRPFLT.[FUNDDocName] = [@FLTUpdateTable].[FUNDDocName]
			  ,BCSTRPFLT.[DatePDFReceivedonFTP] = null
			  ,BCSTRPFLT.[DateFLTRecordHasChanged] = @currentdate
		FROM   BCSTRPFLT
		INNER JOIN @FLTUpdateTable 
			 ON BCSTRPFLT.FUNDCUSIPNUMBER = [@FLTUpdateTable].FUNDCUSIPNUMBER    
				AND BCSTRPFLT.FUNDDocName != [@FLTUpdateTable].FUNDDocName				

 INSERT INTO BCSTRPFLT([FUNDCODE] -- Insert new CUSIP records
      ,[FUNDNAME]
      ,[FUNDTYPE]
      ,[FUNDTELEACCESSCODE]
      ,[FUNDCUSIPNUMBER]
      ,[FUNDCHKHEADINGCODE]
      ,[FUNDGROUPNUMBER]
      ,[FUNDPROSPECTUSINSERT]
      ,[FUNDPROSPECTUSINSERT2]
      ,[FUNDTICKERSYMBOL]
      ,[FUNDDocName]
      ,[DateFLTRecordHasChanged])
  SELECT [FUNDCODE]
      ,[FUNDNAME]
      ,[FUNDTYPE]
      ,[FUNDTELEACCESSCODE]
      ,[FUNDCUSIPNUMBER]
      ,[FUNDCHKHEADINGCODE]
      ,[FUNDGROUPNUMBER]
      ,[FUNDPROSPECTUSINSERT]
      ,[FUNDPROSPECTUSINSERT2]
      ,[FUNDTICKERSYMBOL]
      ,[FUNDDocName]
      ,@currentdate
   FROM @BCSFLTTableDetails BCSFLTTableDetails 
   WHERE [FUNDCUSIPNUMBER] not in
   (SELECT [FUNDCUSIPNUMBER] FROM BCSTRPFLT)
   
   --DELETE BCSTRPFLT -- Delete records that have been removed
   -- WHERE [FUNDCUSIPNUMBER] NOT IN
   -- (SELECT [FUNDCUSIPNUMBER] FROM @BCSFLTTableDetails BCSFLTTableDetails)
   
End